## For local/dev use only - do not use in production
version: "3.7"
services:
  web:
    image:    ajdinmore/php-dev:8.1
    hostname: web
    volumes:
    - ./:/app
    environment:
      DB_NAME:     wordpress
      DB_USER:     wordpress
      DB_PASSWORD: wordpress
      DB_HOST:     db

  db:
    image:    mysql:5.7
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:      wordpress
      MYSQL_USER:          wordpress
      MYSQL_PASSWORD:      wordpress
