## For local dev use only
version: "3.7"
services:
    app:
        image:    ajdinmore/php:8.2-debug
        hostname: app
        tty:      true
        volumes:
            - ./:/app
        environment:
            DB_NAME:     wordpress
            DB_USER:     wordpress
            DB_PASSWORD: wordpress
            DB_HOST:     db
        extra_hosts:
            - host.docker.internal:host-gateway

    server:
        image:    ajdinmore/nginx
        hostname: nginx
        tty:      true
        depends_on:
            - app
        volumes:
            - ./:/app
        environment:
            PHP_HOST: app

    db:
        image:    mysql:8.0
        hostname: db
        tty:      true
        cap_add: [ SYS_NICE ] # stops "mbind: Operation not permitted" log
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE:      wordpress
            MYSQL_USER:          wordpress
            MYSQL_PASSWORD:      wordpress

    assets:
        image:       node:18-alpine
        hostname:    node
        tty:         true
        working_dir: /app
        user:        0:0 # default to root, so we don't have issues running without override file
        command:     sh -c 'npm install && npm run watch'
        volumes:
            - ./:/app
        environment:
            NPM_CONFIG_CACHE:      /tmp/cache
            NPM_CONFIG_USERCONFIG: /tmp/config
