## For local/dev use only - do not use in production
version: "3.7"
services:
    php:
        image:    ajdinmore/php:8.1-dev
        hostname: php
        tty:      true
        volumes:
            - ./:/app
        environment:
            DB_NAME:     wordpress
            DB_USER:     wordpress
            DB_PASSWORD: wordpress
            DB_HOST:     db

    nginx:
        image:    ajdinmore/nginx
        hostname: nginx
        tty:      true
        depends_on:
            - php
        volumes:
            - ./:/app

    db:
        image:    mysql:8.0
        hostname: db
        tty:      true
        cap_add: [ SYS_NICE ] # stops "mbind: Operation not permitted" log
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE:      wordpress
            MYSQL_USER:          wordpress
            MYSQL_PASSWORD:      wordpress
