version: "3.8"
services:
  web:
    image:    ajdinmore/php-dev:8.0
    hostname: web
    ports:
    - ${HTTP_PORT:-80}:80
    volumes:
    - ./:/app
    - ${COMPOSER_HOME:-~/.composer}:/composer
    environment:
      APP_ENV:          ${APP_ENV:-dev}
      URL:              ${URL:-http://localhost}

      DB_NAME:          wordpress
      DB_USER:          wordpress
      DB_PASSWORD:      wordpress
      DB_HOST:          db

      AUTH_KEY:         uniquevalue
      SECURE_AUTH_KEY:  uniquevalue
      LOGGED_IN_KEY:    uniquevalue
      NONCE_KEY:        uniquevalue
      AUTH_SALT:        uniquevalue
      SECURE_AUTH_SALT: uniquevalue
      LOGGED_IN_SALT:   uniquevalue
      NONCE_SALT:       uniquevalue

  db:
    image:    mysql:5.7
    hostname: db
    ports:
    - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:      wordpress
      MYSQL_USER:          wordpress
      MYSQL_PASSWORD:      wordpress
    volumes:
    - .data/db:/var/lib/mysql
