## For local dev use only
version: "3.7"
services:
    app:
        image:    ajdinmore/php:8.2-debug
        hostname: app
        tty:      true
        volumes:
            - ./:/app
        environment:
            DB_NAME:     wordpress
            DB_USER:     wordpress
            DB_PASSWORD: wordpress
            DB_HOST:     db
        extra_hosts:
            - host.docker.internal:host-gateway

    server:
        image:    ajdinmore/nginx
        hostname: nginx
        tty:      true
        depends_on:
            - app
        volumes:
            - ./:/app
        environment:
            PHP_HOST: app

    db:
        image:    mysql:8.0
        hostname: db
        tty:      true
        cap_add: [ SYS_NICE ] # stops "mbind: Operation not permitted" log
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE:      wordpress
            MYSQL_USER:          wordpress
            MYSQL_PASSWORD:      wordpress
